debug output for plotting graph
bug:
ValueError: zero-size array to reduction operation minimum which has no
identity

in:
File "/home/uwe/projects/ludalo/Analysis/plotGraph.py", line 195, in
plotJob

for
588375.intern2